# Site settings
title: Portfolio
description: Portfolio 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SohaEAC
user_description: "Curious by nature, I love to try my hand to new experiences in various domain. I actively seek out new opportunities that will lead me to further success. I am always looking for new challenges. I am used to go beyond my comfort zone"
user_title: Computer Science Student 
email: s.sohaeac@gmail.com
github_username:  sohaeac

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
